version: 2.1
orbs:
    node: circleci/node@5.0.2

jobs:
    build:
        resource_class: small
        executor: node/default # use the default executor defined within the orb
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: npm
            - run:
                  name: Run tests
                  command: npm run test -- --ci --reporters=jest-junit
                  environment:
                      JEST_JUNIT_OUTPUT: ./junit/test-results.xml
            - store_test_results:
                  path: ./junit
            - store_artifacts:
                  path: ./coverage
